[2023-03-30T14:17:16.889+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data scheduled__2023-03-29T14:17:07.272658+00:00 [queued]>
[2023-03-30T14:17:16.896+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data scheduled__2023-03-29T14:17:07.272658+00:00 [queued]>
[2023-03-30T14:17:16.896+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T14:17:16.896+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-30T14:17:16.896+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T14:17:16.917+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): download_citi_bike_data> on 2023-03-29 14:17:07.272658+00:00
[2023-03-30T14:17:16.923+0000] {standard_task_runner.py:55} INFO - Started process 490 to run task
[2023-03-30T14:17:16.930+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'download_citi_bike_data', 'scheduled__2023-03-29T14:17:07.272658+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpqxr0xnzl']
[2023-03-30T14:17:16.931+0000] {standard_task_runner.py:83} INFO - Job 225: Subtask download_citi_bike_data
[2023-03-30T14:17:17.021+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.download_citi_bike_data scheduled__2023-03-29T14:17:07.272658+00:00 [running]> on host ea14cce7ead9
[2023-03-30T14:17:17.084+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=download_citi_bike_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T14:17:07.272658+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T14:17:07.272658+00:00
[2023-03-30T14:17:17.085+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T14:17:17.086+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o /dags/data/202201-citibike-tripdata.csv.zip https://s3.amazonaws.com/tripdata/202201-citibike-tripdata.csv.zip']
[2023-03-30T14:17:17.096+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T14:17:17.103+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-30T14:17:17.103+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-30T14:17:17.857+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 33.9M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2023-03-30T14:17:17.857+0000] {subprocess.py:93} INFO - Warning: /dags/data/202201-citibike-tripdata.csv.zip: No such file or
[2023-03-30T14:17:17.858+0000] {subprocess.py:93} INFO - Warning: directory
[2023-03-30T14:17:17.858+0000] {subprocess.py:93} INFO -   0 33.9M    0 16384    0     0  21729      0  0:27:18 --:--:--  0:27:18 21700
[2023-03-30T14:17:17.858+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-03-30T14:17:17.859+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-03-30T14:17:17.869+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-03-30T14:17:17.873+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=citi_bikes_nyc, task_id=download_citi_bike_data, execution_date=20230329T141707, start_date=20230330T141716, end_date=20230330T141717
[2023-03-30T14:17:17.885+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 225 for task download_citi_bike_data (Bash command failed. The command returned a non-zero exit code 23.; 490)
[2023-03-30T14:17:17.900+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T14:17:17.913+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
