[2023-03-30T15:30:01.360+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [queued]>
[2023-03-30T15:30:01.369+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [queued]>
[2023-03-30T15:30:01.369+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:30:01.369+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-30T15:30:01.369+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:30:01.379+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 15:29:26.735509+00:00
[2023-03-30T15:30:01.386+0000] {standard_task_runner.py:55} INFO - Started process 8244 to run task
[2023-03-30T15:30:01.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T15:29:26.735509+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmptzcaerp7']
[2023-03-30T15:30:01.390+0000] {standard_task_runner.py:83} INFO - Job 257: Subtask unzip_data
[2023-03-30T15:30:01.443+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [running]> on host ea14cce7ead9
[2023-03-30T15:30:01.502+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T15:29:26.735509+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T15:29:26.735509+00:00
[2023-03-30T15:30:01.503+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T15:30:01.504+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'unzip /opt/***/dags/data/202201-citibike-tripdata.csv.zip -d /opt/***/dags/data']
[2023-03-30T15:30:01.516+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T15:30:01.517+0000] {subprocess.py:93} INFO - /bin/bash: line 1: unzip: command not found
[2023-03-30T15:30:01.517+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-30T15:30:01.526+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-30T15:30:01.530+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T152926, start_date=20230330T153001, end_date=20230330T153001
[2023-03-30T15:30:01.540+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 257 for task unzip_data (Bash command failed. The command returned a non-zero exit code 127.; 8244)
[2023-03-30T15:30:01.560+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T15:30:01.580+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
